/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedLecturerIndexRouteImport } from './routes/_authenticated/lecturer/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student/profile'
import { Route as AuthenticatedStudentNotificationsRouteImport } from './routes/_authenticated/student/notifications'
import { Route as AuthenticatedLecturerProfileRouteImport } from './routes/_authenticated/lecturer/profile'
import { Route as AuthenticatedLecturerNotificationsRouteImport } from './routes/_authenticated/lecturer/notifications'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminPdpaRouteImport } from './routes/_authenticated/admin/pdpa'
import { Route as AuthenticatedAdminIntegrityRouteImport } from './routes/_authenticated/admin/integrity'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin/exams'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin/classes'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedStudentExamsIndexRouteImport } from './routes/_authenticated/student/exams.index'
import { Route as AuthenticatedStudentClassesIndexRouteImport } from './routes/_authenticated/student/classes.index'
import { Route as AuthenticatedStudentAppealsIndexRouteImport } from './routes/_authenticated/student/appeals.index'
import { Route as AuthenticatedLecturerQuestionBankIndexRouteImport } from './routes/_authenticated/lecturer/question-bank.index'
import { Route as AuthenticatedLecturerExamsIndexRouteImport } from './routes/_authenticated/lecturer/exams.index'
import { Route as AuthenticatedLecturerClassesIndexRouteImport } from './routes/_authenticated/lecturer/classes.index'
import { Route as AuthenticatedLecturerAppealsIndexRouteImport } from './routes/_authenticated/lecturer/appeals.index'
import { Route as AuthenticatedStudentClassesClassIdRouteImport } from './routes/_authenticated/student/classes.$classId'
import { Route as AuthenticatedStudentAppealsScoreRouteImport } from './routes/_authenticated/student/appeals.score'
import { Route as AuthenticatedStudentAppealsNewRouteImport } from './routes/_authenticated/student/appeals.new'
import { Route as AuthenticatedStudentAppealsIntegrityRouteImport } from './routes/_authenticated/student/appeals.integrity'
import { Route as AuthenticatedLecturerQuestionBankNewRouteImport } from './routes/_authenticated/lecturer/question-bank.new'
import { Route as AuthenticatedLecturerExamsNewRouteImport } from './routes/_authenticated/lecturer/exams.new'
import { Route as AuthenticatedLecturerClassesClassIdRouteImport } from './routes/_authenticated/lecturer/classes.$classId'
import { Route as AuthenticatedStudentExamsExamIdTakeRouteImport } from './routes/_authenticated/student/exams.$examId.take'
import { Route as AuthenticatedStudentExamsExamIdSubmitConfirmRouteImport } from './routes/_authenticated/student/exams.$examId.submit-confirm'
import { Route as AuthenticatedStudentExamsExamIdResultRouteImport } from './routes/_authenticated/student/exams.$examId.result'
import { Route as AuthenticatedStudentExamsExamIdLobbyRouteImport } from './routes/_authenticated/student/exams.$examId.lobby'
import { Route as AuthenticatedLecturerQuestionBankIdEditRouteImport } from './routes/_authenticated/lecturer/question-bank.$id.edit'
import { Route as AuthenticatedLecturerExamsExamIdResultsRouteImport } from './routes/_authenticated/lecturer/exams.$examId.results'
import { Route as AuthenticatedLecturerExamsExamIdMonitorRouteImport } from './routes/_authenticated/lecturer/exams.$examId.monitor'
import { Route as AuthenticatedLecturerExamsExamIdEditRouteImport } from './routes/_authenticated/lecturer/exams.$examId.edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerIndexRoute =
  AuthenticatedLecturerIndexRouteImport.update({
    id: '/lecturer/',
    path: '/lecturer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentNotificationsRoute =
  AuthenticatedStudentNotificationsRouteImport.update({
    id: '/student/notifications',
    path: '/student/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerProfileRoute =
  AuthenticatedLecturerProfileRouteImport.update({
    id: '/lecturer/profile',
    path: '/lecturer/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerNotificationsRoute =
  AuthenticatedLecturerNotificationsRouteImport.update({
    id: '/lecturer/notifications',
    path: '/lecturer/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPdpaRoute = AuthenticatedAdminPdpaRouteImport.update({
  id: '/admin/pdpa',
  path: '/admin/pdpa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIntegrityRoute =
  AuthenticatedAdminIntegrityRouteImport.update({
    id: '/admin/integrity',
    path: '/admin/integrity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/admin/classes',
    path: '/admin/classes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/admin/audit-log',
    path: '/admin/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentExamsIndexRoute =
  AuthenticatedStudentExamsIndexRouteImport.update({
    id: '/student/exams/',
    path: '/student/exams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentClassesIndexRoute =
  AuthenticatedStudentClassesIndexRouteImport.update({
    id: '/student/classes/',
    path: '/student/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAppealsIndexRoute =
  AuthenticatedStudentAppealsIndexRouteImport.update({
    id: '/student/appeals/',
    path: '/student/appeals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerQuestionBankIndexRoute =
  AuthenticatedLecturerQuestionBankIndexRouteImport.update({
    id: '/lecturer/question-bank/',
    path: '/lecturer/question-bank/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerExamsIndexRoute =
  AuthenticatedLecturerExamsIndexRouteImport.update({
    id: '/lecturer/exams/',
    path: '/lecturer/exams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerClassesIndexRoute =
  AuthenticatedLecturerClassesIndexRouteImport.update({
    id: '/lecturer/classes/',
    path: '/lecturer/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerAppealsIndexRoute =
  AuthenticatedLecturerAppealsIndexRouteImport.update({
    id: '/lecturer/appeals/',
    path: '/lecturer/appeals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentClassesClassIdRoute =
  AuthenticatedStudentClassesClassIdRouteImport.update({
    id: '/student/classes/$classId',
    path: '/student/classes/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAppealsScoreRoute =
  AuthenticatedStudentAppealsScoreRouteImport.update({
    id: '/student/appeals/score',
    path: '/student/appeals/score',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAppealsNewRoute =
  AuthenticatedStudentAppealsNewRouteImport.update({
    id: '/student/appeals/new',
    path: '/student/appeals/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAppealsIntegrityRoute =
  AuthenticatedStudentAppealsIntegrityRouteImport.update({
    id: '/student/appeals/integrity',
    path: '/student/appeals/integrity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerQuestionBankNewRoute =
  AuthenticatedLecturerQuestionBankNewRouteImport.update({
    id: '/lecturer/question-bank/new',
    path: '/lecturer/question-bank/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerExamsNewRoute =
  AuthenticatedLecturerExamsNewRouteImport.update({
    id: '/lecturer/exams/new',
    path: '/lecturer/exams/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerClassesClassIdRoute =
  AuthenticatedLecturerClassesClassIdRouteImport.update({
    id: '/lecturer/classes/$classId',
    path: '/lecturer/classes/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentExamsExamIdTakeRoute =
  AuthenticatedStudentExamsExamIdTakeRouteImport.update({
    id: '/student/exams/$examId/take',
    path: '/student/exams/$examId/take',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentExamsExamIdSubmitConfirmRoute =
  AuthenticatedStudentExamsExamIdSubmitConfirmRouteImport.update({
    id: '/student/exams/$examId/submit-confirm',
    path: '/student/exams/$examId/submit-confirm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentExamsExamIdResultRoute =
  AuthenticatedStudentExamsExamIdResultRouteImport.update({
    id: '/student/exams/$examId/result',
    path: '/student/exams/$examId/result',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentExamsExamIdLobbyRoute =
  AuthenticatedStudentExamsExamIdLobbyRouteImport.update({
    id: '/student/exams/$examId/lobby',
    path: '/student/exams/$examId/lobby',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerQuestionBankIdEditRoute =
  AuthenticatedLecturerQuestionBankIdEditRouteImport.update({
    id: '/lecturer/question-bank/$id/edit',
    path: '/lecturer/question-bank/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerExamsExamIdResultsRoute =
  AuthenticatedLecturerExamsExamIdResultsRouteImport.update({
    id: '/lecturer/exams/$examId/results',
    path: '/lecturer/exams/$examId/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerExamsExamIdMonitorRoute =
  AuthenticatedLecturerExamsExamIdMonitorRouteImport.update({
    id: '/lecturer/exams/$examId/monitor',
    path: '/lecturer/exams/$examId/monitor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLecturerExamsExamIdEditRoute =
  AuthenticatedLecturerExamsExamIdEditRouteImport.update({
    id: '/lecturer/exams/$examId/edit',
    path: '/lecturer/exams/$examId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/philosophy': typeof PhilosophyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/integrity': typeof AuthenticatedAdminIntegrityRoute
  '/admin/pdpa': typeof AuthenticatedAdminPdpaRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lecturer/notifications': typeof AuthenticatedLecturerNotificationsRoute
  '/lecturer/profile': typeof AuthenticatedLecturerProfileRoute
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lecturer/': typeof AuthenticatedLecturerIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/lecturer/classes/$classId': typeof AuthenticatedLecturerClassesClassIdRoute
  '/lecturer/exams/new': typeof AuthenticatedLecturerExamsNewRoute
  '/lecturer/question-bank/new': typeof AuthenticatedLecturerQuestionBankNewRoute
  '/student/appeals/integrity': typeof AuthenticatedStudentAppealsIntegrityRoute
  '/student/appeals/new': typeof AuthenticatedStudentAppealsNewRoute
  '/student/appeals/score': typeof AuthenticatedStudentAppealsScoreRoute
  '/student/classes/$classId': typeof AuthenticatedStudentClassesClassIdRoute
  '/lecturer/appeals/': typeof AuthenticatedLecturerAppealsIndexRoute
  '/lecturer/classes/': typeof AuthenticatedLecturerClassesIndexRoute
  '/lecturer/exams/': typeof AuthenticatedLecturerExamsIndexRoute
  '/lecturer/question-bank/': typeof AuthenticatedLecturerQuestionBankIndexRoute
  '/student/appeals/': typeof AuthenticatedStudentAppealsIndexRoute
  '/student/classes/': typeof AuthenticatedStudentClassesIndexRoute
  '/student/exams/': typeof AuthenticatedStudentExamsIndexRoute
  '/lecturer/exams/$examId/edit': typeof AuthenticatedLecturerExamsExamIdEditRoute
  '/lecturer/exams/$examId/monitor': typeof AuthenticatedLecturerExamsExamIdMonitorRoute
  '/lecturer/exams/$examId/results': typeof AuthenticatedLecturerExamsExamIdResultsRoute
  '/lecturer/question-bank/$id/edit': typeof AuthenticatedLecturerQuestionBankIdEditRoute
  '/student/exams/$examId/lobby': typeof AuthenticatedStudentExamsExamIdLobbyRoute
  '/student/exams/$examId/result': typeof AuthenticatedStudentExamsExamIdResultRoute
  '/student/exams/$examId/submit-confirm': typeof AuthenticatedStudentExamsExamIdSubmitConfirmRoute
  '/student/exams/$examId/take': typeof AuthenticatedStudentExamsExamIdTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/philosophy': typeof PhilosophyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/integrity': typeof AuthenticatedAdminIntegrityRoute
  '/admin/pdpa': typeof AuthenticatedAdminPdpaRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lecturer/notifications': typeof AuthenticatedLecturerNotificationsRoute
  '/lecturer/profile': typeof AuthenticatedLecturerProfileRoute
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lecturer': typeof AuthenticatedLecturerIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/lecturer/classes/$classId': typeof AuthenticatedLecturerClassesClassIdRoute
  '/lecturer/exams/new': typeof AuthenticatedLecturerExamsNewRoute
  '/lecturer/question-bank/new': typeof AuthenticatedLecturerQuestionBankNewRoute
  '/student/appeals/integrity': typeof AuthenticatedStudentAppealsIntegrityRoute
  '/student/appeals/new': typeof AuthenticatedStudentAppealsNewRoute
  '/student/appeals/score': typeof AuthenticatedStudentAppealsScoreRoute
  '/student/classes/$classId': typeof AuthenticatedStudentClassesClassIdRoute
  '/lecturer/appeals': typeof AuthenticatedLecturerAppealsIndexRoute
  '/lecturer/classes': typeof AuthenticatedLecturerClassesIndexRoute
  '/lecturer/exams': typeof AuthenticatedLecturerExamsIndexRoute
  '/lecturer/question-bank': typeof AuthenticatedLecturerQuestionBankIndexRoute
  '/student/appeals': typeof AuthenticatedStudentAppealsIndexRoute
  '/student/classes': typeof AuthenticatedStudentClassesIndexRoute
  '/student/exams': typeof AuthenticatedStudentExamsIndexRoute
  '/lecturer/exams/$examId/edit': typeof AuthenticatedLecturerExamsExamIdEditRoute
  '/lecturer/exams/$examId/monitor': typeof AuthenticatedLecturerExamsExamIdMonitorRoute
  '/lecturer/exams/$examId/results': typeof AuthenticatedLecturerExamsExamIdResultsRoute
  '/lecturer/question-bank/$id/edit': typeof AuthenticatedLecturerQuestionBankIdEditRoute
  '/student/exams/$examId/lobby': typeof AuthenticatedStudentExamsExamIdLobbyRoute
  '/student/exams/$examId/result': typeof AuthenticatedStudentExamsExamIdResultRoute
  '/student/exams/$examId/submit-confirm': typeof AuthenticatedStudentExamsExamIdSubmitConfirmRoute
  '/student/exams/$examId/take': typeof AuthenticatedStudentExamsExamIdTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/philosophy': typeof PhilosophyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/_authenticated/admin/integrity': typeof AuthenticatedAdminIntegrityRoute
  '/_authenticated/admin/pdpa': typeof AuthenticatedAdminPdpaRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/lecturer/notifications': typeof AuthenticatedLecturerNotificationsRoute
  '/_authenticated/lecturer/profile': typeof AuthenticatedLecturerProfileRoute
  '/_authenticated/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/lecturer/': typeof AuthenticatedLecturerIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/lecturer/classes/$classId': typeof AuthenticatedLecturerClassesClassIdRoute
  '/_authenticated/lecturer/exams/new': typeof AuthenticatedLecturerExamsNewRoute
  '/_authenticated/lecturer/question-bank/new': typeof AuthenticatedLecturerQuestionBankNewRoute
  '/_authenticated/student/appeals/integrity': typeof AuthenticatedStudentAppealsIntegrityRoute
  '/_authenticated/student/appeals/new': typeof AuthenticatedStudentAppealsNewRoute
  '/_authenticated/student/appeals/score': typeof AuthenticatedStudentAppealsScoreRoute
  '/_authenticated/student/classes/$classId': typeof AuthenticatedStudentClassesClassIdRoute
  '/_authenticated/lecturer/appeals/': typeof AuthenticatedLecturerAppealsIndexRoute
  '/_authenticated/lecturer/classes/': typeof AuthenticatedLecturerClassesIndexRoute
  '/_authenticated/lecturer/exams/': typeof AuthenticatedLecturerExamsIndexRoute
  '/_authenticated/lecturer/question-bank/': typeof AuthenticatedLecturerQuestionBankIndexRoute
  '/_authenticated/student/appeals/': typeof AuthenticatedStudentAppealsIndexRoute
  '/_authenticated/student/classes/': typeof AuthenticatedStudentClassesIndexRoute
  '/_authenticated/student/exams/': typeof AuthenticatedStudentExamsIndexRoute
  '/_authenticated/lecturer/exams/$examId/edit': typeof AuthenticatedLecturerExamsExamIdEditRoute
  '/_authenticated/lecturer/exams/$examId/monitor': typeof AuthenticatedLecturerExamsExamIdMonitorRoute
  '/_authenticated/lecturer/exams/$examId/results': typeof AuthenticatedLecturerExamsExamIdResultsRoute
  '/_authenticated/lecturer/question-bank/$id/edit': typeof AuthenticatedLecturerQuestionBankIdEditRoute
  '/_authenticated/student/exams/$examId/lobby': typeof AuthenticatedStudentExamsExamIdLobbyRoute
  '/_authenticated/student/exams/$examId/result': typeof AuthenticatedStudentExamsExamIdResultRoute
  '/_authenticated/student/exams/$examId/submit-confirm': typeof AuthenticatedStudentExamsExamIdSubmitConfirmRoute
  '/_authenticated/student/exams/$examId/take': typeof AuthenticatedStudentExamsExamIdTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/philosophy'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/audit-log'
    | '/admin/classes'
    | '/admin/exams'
    | '/admin/integrity'
    | '/admin/pdpa'
    | '/admin/settings'
    | '/admin/users'
    | '/lecturer/notifications'
    | '/lecturer/profile'
    | '/student/notifications'
    | '/student/profile'
    | '/admin/'
    | '/lecturer/'
    | '/student/'
    | '/lecturer/classes/$classId'
    | '/lecturer/exams/new'
    | '/lecturer/question-bank/new'
    | '/student/appeals/integrity'
    | '/student/appeals/new'
    | '/student/appeals/score'
    | '/student/classes/$classId'
    | '/lecturer/appeals/'
    | '/lecturer/classes/'
    | '/lecturer/exams/'
    | '/lecturer/question-bank/'
    | '/student/appeals/'
    | '/student/classes/'
    | '/student/exams/'
    | '/lecturer/exams/$examId/edit'
    | '/lecturer/exams/$examId/monitor'
    | '/lecturer/exams/$examId/results'
    | '/lecturer/question-bank/$id/edit'
    | '/student/exams/$examId/lobby'
    | '/student/exams/$examId/result'
    | '/student/exams/$examId/submit-confirm'
    | '/student/exams/$examId/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/philosophy'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/audit-log'
    | '/admin/classes'
    | '/admin/exams'
    | '/admin/integrity'
    | '/admin/pdpa'
    | '/admin/settings'
    | '/admin/users'
    | '/lecturer/notifications'
    | '/lecturer/profile'
    | '/student/notifications'
    | '/student/profile'
    | '/admin'
    | '/lecturer'
    | '/student'
    | '/lecturer/classes/$classId'
    | '/lecturer/exams/new'
    | '/lecturer/question-bank/new'
    | '/student/appeals/integrity'
    | '/student/appeals/new'
    | '/student/appeals/score'
    | '/student/classes/$classId'
    | '/lecturer/appeals'
    | '/lecturer/classes'
    | '/lecturer/exams'
    | '/lecturer/question-bank'
    | '/student/appeals'
    | '/student/classes'
    | '/student/exams'
    | '/lecturer/exams/$examId/edit'
    | '/lecturer/exams/$examId/monitor'
    | '/lecturer/exams/$examId/results'
    | '/lecturer/question-bank/$id/edit'
    | '/student/exams/$examId/lobby'
    | '/student/exams/$examId/result'
    | '/student/exams/$examId/submit-confirm'
    | '/student/exams/$examId/take'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/philosophy'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/integrity'
    | '/_authenticated/admin/pdpa'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/lecturer/notifications'
    | '/_authenticated/lecturer/profile'
    | '/_authenticated/student/notifications'
    | '/_authenticated/student/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/lecturer/'
    | '/_authenticated/student/'
    | '/_authenticated/lecturer/classes/$classId'
    | '/_authenticated/lecturer/exams/new'
    | '/_authenticated/lecturer/question-bank/new'
    | '/_authenticated/student/appeals/integrity'
    | '/_authenticated/student/appeals/new'
    | '/_authenticated/student/appeals/score'
    | '/_authenticated/student/classes/$classId'
    | '/_authenticated/lecturer/appeals/'
    | '/_authenticated/lecturer/classes/'
    | '/_authenticated/lecturer/exams/'
    | '/_authenticated/lecturer/question-bank/'
    | '/_authenticated/student/appeals/'
    | '/_authenticated/student/classes/'
    | '/_authenticated/student/exams/'
    | '/_authenticated/lecturer/exams/$examId/edit'
    | '/_authenticated/lecturer/exams/$examId/monitor'
    | '/_authenticated/lecturer/exams/$examId/results'
    | '/_authenticated/lecturer/question-bank/$id/edit'
    | '/_authenticated/student/exams/$examId/lobby'
    | '/_authenticated/student/exams/$examId/result'
    | '/_authenticated/student/exams/$examId/submit-confirm'
    | '/_authenticated/student/exams/$examId/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PhilosophyRoute: typeof PhilosophyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/': {
      id: '/_authenticated/lecturer/'
      path: '/lecturer'
      fullPath: '/lecturer/'
      preLoaderRoute: typeof AuthenticatedLecturerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/notifications': {
      id: '/_authenticated/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof AuthenticatedStudentNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/profile': {
      id: '/_authenticated/lecturer/profile'
      path: '/lecturer/profile'
      fullPath: '/lecturer/profile'
      preLoaderRoute: typeof AuthenticatedLecturerProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/notifications': {
      id: '/_authenticated/lecturer/notifications'
      path: '/lecturer/notifications'
      fullPath: '/lecturer/notifications'
      preLoaderRoute: typeof AuthenticatedLecturerNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pdpa': {
      id: '/_authenticated/admin/pdpa'
      path: '/admin/pdpa'
      fullPath: '/admin/pdpa'
      preLoaderRoute: typeof AuthenticatedAdminPdpaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/integrity': {
      id: '/_authenticated/admin/integrity'
      path: '/admin/integrity'
      fullPath: '/admin/integrity'
      preLoaderRoute: typeof AuthenticatedAdminIntegrityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/admin/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/exams/': {
      id: '/_authenticated/student/exams/'
      path: '/student/exams'
      fullPath: '/student/exams/'
      preLoaderRoute: typeof AuthenticatedStudentExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/classes/': {
      id: '/_authenticated/student/classes/'
      path: '/student/classes'
      fullPath: '/student/classes/'
      preLoaderRoute: typeof AuthenticatedStudentClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/appeals/': {
      id: '/_authenticated/student/appeals/'
      path: '/student/appeals'
      fullPath: '/student/appeals/'
      preLoaderRoute: typeof AuthenticatedStudentAppealsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/question-bank/': {
      id: '/_authenticated/lecturer/question-bank/'
      path: '/lecturer/question-bank'
      fullPath: '/lecturer/question-bank/'
      preLoaderRoute: typeof AuthenticatedLecturerQuestionBankIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/exams/': {
      id: '/_authenticated/lecturer/exams/'
      path: '/lecturer/exams'
      fullPath: '/lecturer/exams/'
      preLoaderRoute: typeof AuthenticatedLecturerExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/classes/': {
      id: '/_authenticated/lecturer/classes/'
      path: '/lecturer/classes'
      fullPath: '/lecturer/classes/'
      preLoaderRoute: typeof AuthenticatedLecturerClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/appeals/': {
      id: '/_authenticated/lecturer/appeals/'
      path: '/lecturer/appeals'
      fullPath: '/lecturer/appeals/'
      preLoaderRoute: typeof AuthenticatedLecturerAppealsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/classes/$classId': {
      id: '/_authenticated/student/classes/$classId'
      path: '/student/classes/$classId'
      fullPath: '/student/classes/$classId'
      preLoaderRoute: typeof AuthenticatedStudentClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/appeals/score': {
      id: '/_authenticated/student/appeals/score'
      path: '/student/appeals/score'
      fullPath: '/student/appeals/score'
      preLoaderRoute: typeof AuthenticatedStudentAppealsScoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/appeals/new': {
      id: '/_authenticated/student/appeals/new'
      path: '/student/appeals/new'
      fullPath: '/student/appeals/new'
      preLoaderRoute: typeof AuthenticatedStudentAppealsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/appeals/integrity': {
      id: '/_authenticated/student/appeals/integrity'
      path: '/student/appeals/integrity'
      fullPath: '/student/appeals/integrity'
      preLoaderRoute: typeof AuthenticatedStudentAppealsIntegrityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/question-bank/new': {
      id: '/_authenticated/lecturer/question-bank/new'
      path: '/lecturer/question-bank/new'
      fullPath: '/lecturer/question-bank/new'
      preLoaderRoute: typeof AuthenticatedLecturerQuestionBankNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/exams/new': {
      id: '/_authenticated/lecturer/exams/new'
      path: '/lecturer/exams/new'
      fullPath: '/lecturer/exams/new'
      preLoaderRoute: typeof AuthenticatedLecturerExamsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/classes/$classId': {
      id: '/_authenticated/lecturer/classes/$classId'
      path: '/lecturer/classes/$classId'
      fullPath: '/lecturer/classes/$classId'
      preLoaderRoute: typeof AuthenticatedLecturerClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/exams/$examId/take': {
      id: '/_authenticated/student/exams/$examId/take'
      path: '/student/exams/$examId/take'
      fullPath: '/student/exams/$examId/take'
      preLoaderRoute: typeof AuthenticatedStudentExamsExamIdTakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/exams/$examId/submit-confirm': {
      id: '/_authenticated/student/exams/$examId/submit-confirm'
      path: '/student/exams/$examId/submit-confirm'
      fullPath: '/student/exams/$examId/submit-confirm'
      preLoaderRoute: typeof AuthenticatedStudentExamsExamIdSubmitConfirmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/exams/$examId/result': {
      id: '/_authenticated/student/exams/$examId/result'
      path: '/student/exams/$examId/result'
      fullPath: '/student/exams/$examId/result'
      preLoaderRoute: typeof AuthenticatedStudentExamsExamIdResultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/exams/$examId/lobby': {
      id: '/_authenticated/student/exams/$examId/lobby'
      path: '/student/exams/$examId/lobby'
      fullPath: '/student/exams/$examId/lobby'
      preLoaderRoute: typeof AuthenticatedStudentExamsExamIdLobbyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/question-bank/$id/edit': {
      id: '/_authenticated/lecturer/question-bank/$id/edit'
      path: '/lecturer/question-bank/$id/edit'
      fullPath: '/lecturer/question-bank/$id/edit'
      preLoaderRoute: typeof AuthenticatedLecturerQuestionBankIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/exams/$examId/results': {
      id: '/_authenticated/lecturer/exams/$examId/results'
      path: '/lecturer/exams/$examId/results'
      fullPath: '/lecturer/exams/$examId/results'
      preLoaderRoute: typeof AuthenticatedLecturerExamsExamIdResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/exams/$examId/monitor': {
      id: '/_authenticated/lecturer/exams/$examId/monitor'
      path: '/lecturer/exams/$examId/monitor'
      fullPath: '/lecturer/exams/$examId/monitor'
      preLoaderRoute: typeof AuthenticatedLecturerExamsExamIdMonitorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lecturer/exams/$examId/edit': {
      id: '/_authenticated/lecturer/exams/$examId/edit'
      path: '/lecturer/exams/$examId/edit'
      fullPath: '/lecturer/exams/$examId/edit'
      preLoaderRoute: typeof AuthenticatedLecturerExamsExamIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRoute
  AuthenticatedAdminIntegrityRoute: typeof AuthenticatedAdminIntegrityRoute
  AuthenticatedAdminPdpaRoute: typeof AuthenticatedAdminPdpaRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedLecturerNotificationsRoute: typeof AuthenticatedLecturerNotificationsRoute
  AuthenticatedLecturerProfileRoute: typeof AuthenticatedLecturerProfileRoute
  AuthenticatedStudentNotificationsRoute: typeof AuthenticatedStudentNotificationsRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedLecturerIndexRoute: typeof AuthenticatedLecturerIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedLecturerClassesClassIdRoute: typeof AuthenticatedLecturerClassesClassIdRoute
  AuthenticatedLecturerExamsNewRoute: typeof AuthenticatedLecturerExamsNewRoute
  AuthenticatedLecturerQuestionBankNewRoute: typeof AuthenticatedLecturerQuestionBankNewRoute
  AuthenticatedStudentAppealsIntegrityRoute: typeof AuthenticatedStudentAppealsIntegrityRoute
  AuthenticatedStudentAppealsNewRoute: typeof AuthenticatedStudentAppealsNewRoute
  AuthenticatedStudentAppealsScoreRoute: typeof AuthenticatedStudentAppealsScoreRoute
  AuthenticatedStudentClassesClassIdRoute: typeof AuthenticatedStudentClassesClassIdRoute
  AuthenticatedLecturerAppealsIndexRoute: typeof AuthenticatedLecturerAppealsIndexRoute
  AuthenticatedLecturerClassesIndexRoute: typeof AuthenticatedLecturerClassesIndexRoute
  AuthenticatedLecturerExamsIndexRoute: typeof AuthenticatedLecturerExamsIndexRoute
  AuthenticatedLecturerQuestionBankIndexRoute: typeof AuthenticatedLecturerQuestionBankIndexRoute
  AuthenticatedStudentAppealsIndexRoute: typeof AuthenticatedStudentAppealsIndexRoute
  AuthenticatedStudentClassesIndexRoute: typeof AuthenticatedStudentClassesIndexRoute
  AuthenticatedStudentExamsIndexRoute: typeof AuthenticatedStudentExamsIndexRoute
  AuthenticatedLecturerExamsExamIdEditRoute: typeof AuthenticatedLecturerExamsExamIdEditRoute
  AuthenticatedLecturerExamsExamIdMonitorRoute: typeof AuthenticatedLecturerExamsExamIdMonitorRoute
  AuthenticatedLecturerExamsExamIdResultsRoute: typeof AuthenticatedLecturerExamsExamIdResultsRoute
  AuthenticatedLecturerQuestionBankIdEditRoute: typeof AuthenticatedLecturerQuestionBankIdEditRoute
  AuthenticatedStudentExamsExamIdLobbyRoute: typeof AuthenticatedStudentExamsExamIdLobbyRoute
  AuthenticatedStudentExamsExamIdResultRoute: typeof AuthenticatedStudentExamsExamIdResultRoute
  AuthenticatedStudentExamsExamIdSubmitConfirmRoute: typeof AuthenticatedStudentExamsExamIdSubmitConfirmRoute
  AuthenticatedStudentExamsExamIdTakeRoute: typeof AuthenticatedStudentExamsExamIdTakeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRoute,
  AuthenticatedAdminIntegrityRoute: AuthenticatedAdminIntegrityRoute,
  AuthenticatedAdminPdpaRoute: AuthenticatedAdminPdpaRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedLecturerNotificationsRoute:
    AuthenticatedLecturerNotificationsRoute,
  AuthenticatedLecturerProfileRoute: AuthenticatedLecturerProfileRoute,
  AuthenticatedStudentNotificationsRoute:
    AuthenticatedStudentNotificationsRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedLecturerIndexRoute: AuthenticatedLecturerIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedLecturerClassesClassIdRoute:
    AuthenticatedLecturerClassesClassIdRoute,
  AuthenticatedLecturerExamsNewRoute: AuthenticatedLecturerExamsNewRoute,
  AuthenticatedLecturerQuestionBankNewRoute:
    AuthenticatedLecturerQuestionBankNewRoute,
  AuthenticatedStudentAppealsIntegrityRoute:
    AuthenticatedStudentAppealsIntegrityRoute,
  AuthenticatedStudentAppealsNewRoute: AuthenticatedStudentAppealsNewRoute,
  AuthenticatedStudentAppealsScoreRoute: AuthenticatedStudentAppealsScoreRoute,
  AuthenticatedStudentClassesClassIdRoute:
    AuthenticatedStudentClassesClassIdRoute,
  AuthenticatedLecturerAppealsIndexRoute:
    AuthenticatedLecturerAppealsIndexRoute,
  AuthenticatedLecturerClassesIndexRoute:
    AuthenticatedLecturerClassesIndexRoute,
  AuthenticatedLecturerExamsIndexRoute: AuthenticatedLecturerExamsIndexRoute,
  AuthenticatedLecturerQuestionBankIndexRoute:
    AuthenticatedLecturerQuestionBankIndexRoute,
  AuthenticatedStudentAppealsIndexRoute: AuthenticatedStudentAppealsIndexRoute,
  AuthenticatedStudentClassesIndexRoute: AuthenticatedStudentClassesIndexRoute,
  AuthenticatedStudentExamsIndexRoute: AuthenticatedStudentExamsIndexRoute,
  AuthenticatedLecturerExamsExamIdEditRoute:
    AuthenticatedLecturerExamsExamIdEditRoute,
  AuthenticatedLecturerExamsExamIdMonitorRoute:
    AuthenticatedLecturerExamsExamIdMonitorRoute,
  AuthenticatedLecturerExamsExamIdResultsRoute:
    AuthenticatedLecturerExamsExamIdResultsRoute,
  AuthenticatedLecturerQuestionBankIdEditRoute:
    AuthenticatedLecturerQuestionBankIdEditRoute,
  AuthenticatedStudentExamsExamIdLobbyRoute:
    AuthenticatedStudentExamsExamIdLobbyRoute,
  AuthenticatedStudentExamsExamIdResultRoute:
    AuthenticatedStudentExamsExamIdResultRoute,
  AuthenticatedStudentExamsExamIdSubmitConfirmRoute:
    AuthenticatedStudentExamsExamIdSubmitConfirmRoute,
  AuthenticatedStudentExamsExamIdTakeRoute:
    AuthenticatedStudentExamsExamIdTakeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PhilosophyRoute: PhilosophyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
